@startuml
'https://plantuml.com/sequence-diagram

actor Balconista as B
participant Sistema as S
autonumber

activate B
B --> S : Inicia o processo de criação de um catálogo
activate S

S --> B : Pergunta se o catálago será organizado pela Categoria, Descrição ou marca
deactivate S
B --> S: Insere a informação pedida
activate S
S --> B : mostra a informação relativa ao catálago criado
deactivate S
deactivate B
@enduml